# -*- coding: utf-8 -*-
"""FACE recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J5wvD6chPuUdDdxnD07CXk2YcDJJqy6U
"""

import cv2
import face_recognition
img1=face_recognition.load_image_file('/content/bjp.jpg')
img1=cv2.cvtColor(img1,cv2.COLOR_BGR2RGB)

!pip install face_recognition



from google.colab.patches import cv2_imshow

from google.colab.patches import cv2_imshow
cv2_imshow(img1)

img1test=face_recognition.load_image_file('/content/channels4_profile.jpg')
img1test=cv2.cvtColor(img1test,cv2.COLOR_BGR2RGB)

from google.colab.patches import cv2_imshow
cv2_imshow(img1test)

face=face_recognition.face_locations(img1)[0]
print(face)

encodeFace=face_recognition.face_encodings(img1)[0]

print(encodeFace)

cv2.rectangle(img1,(face[3],face[0]),(face[1],face[2]),(0,255,0),3)



#cv2_imshow(img1)

faceTest=face_recognition.face_locations(img1test)[0]
encodeTestFace=face_recognition.face_encodings(img1test)[0]
cv2.rectangle(img1test,(faceTest[3],faceTest[0]),(faceTest[1],faceTest[2]),(0,255,0),3)[0]

from google.colab.patches import cv2_imshow
cv2_imshow(img1test)

res=face_recognition.compare_faces([encodeFace],encodeTestFace)

res

face_dis=face_recognition.face_distance([encodeFace],encodeTestFace)
print(res,face_dis)

cv2.putText(img1test,f"{res} {round(face_dis[0],2)}",(5,50),cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),2)



from google.colab.patches import cv2_imshow
cv2_imshow(img1test)

!git init

!git clone https://github.com/chandan19217/face-recognition

! pwdd

!pwd

! git remote -v

! git status

! python myfile.py

